### ISSUE TITLE
串口利能接收到数据，为什么UI里不更新啊

### ISSUE THREAD

**Issue by cybergeek2077** [potterhere/FreescalePlatform#1]
下位机用的最新的k60代码，只改了发送和 接收地址，上位机串口里能看到接受到6个实时参数正确的数据，就是ui里不会更新啊

**Comment by Sudouble** [comment]
可以看一下串口里发送的数据吗？串口设置那边需要按照ASCII方式进行显示。

**Comment by cybergeek2077** [comment]
![image](https://cloud.githubusercontent.com/assets/17921838/14912327/f60e3afc-0e2d-11e6-88c2-ca684586cba6.png)

**Comment by cybergeek2077** [comment]
![image](https://cloud.githubusercontent.com/assets/17921838/14912367/47dac9d6-0e2e-11e6-8a1e-593083ef945b.png)

**Comment by cybergeek2077** [comment]
不知道为啥有的多了一个箭头

**Comment by Sudouble** [comment]
运行 Debug 里的版本试试，那个是最新的。
使用的时候：”十六进制显示“、”自动换行显示“ 都不勾选试试

**Comment by cybergeek2077** [comment]
还是不行啊，留个qq吧

**Comment by Sudouble** [comment]
好的，361958654
